name: Build-test

on:
  push:
    branches: [ "main", "dev" ]
  pull_request:
    branches: [ "main", "dev" ]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Update package repositories
      run: sudo apt update
    - name: Run ./setup.sh
      run: sudo bash ./setup.sh
    - name: Test help and version arguments
      run: |
        # Help
        oawp -h
        oawp -help
        oawp --help
        # Version
        oawp -v
        oawp -version
        oawp --version
